image: node:12

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -rf * .public
    - echo "cp public successful"
    - mv .public public

  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - docker
